name: JHapy Shared Commons CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo Build for SHA = ${{ github.event.client_payload.sha }}, REF = ${{ github.event.client_payload.ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jhapy/**
          key: ${{ runner.os }}-maven-shared-commons
          restore-keys: |
            ${{ runner.os }}-maven-shared-commons
      - name: Clean Maven Repository
        run: rm -rf ~/.m2/repository/org/jhapy
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY:
            ${{ secrets.GPG_SIGNING_KEY }}
      - name: Build with Maven
        run: mvn -Dmaven.test.skip -s .settings.xml -Dmaven.javadoc.skip -Dossrh_username=${{secrets.ossrh_username}} -Dossrh_password=${{secrets.ossrh_password}} --file pom.xml deploy
      - name: Workflow Dispatch to utils-registry-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/utils-registry-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy Utils Registry Server CI
      - name: Workflow Dispatch to utils-registry-server K8S repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/utils-registry-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy Utils Registry Server K8S CI
      - name: Workflow Dispatch to app-base-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-base-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Base Server CI
      - name: Workflow Dispatch to app-audit-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-audit-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Audit Server CI
      - name: Workflow Dispatch to app-audit-server K8S repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-audit-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Audit Server K8S CI
      - name: Workflow Dispatch to app-i18n-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-i18n-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App I18N Server CI
      - name: Workflow Dispatch to app-i18n-server K8S repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-i18n-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App I18N Server K8S CI
      - name: Workflow Dispatch to app-resource-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-resource-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Resource Server CI
      - name: Workflow Dispatch to app-resource-server K8S repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-resource-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Resource Server K8S CI
      - name: Workflow Dispatch to app-notification-server repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-notification-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Notification Server CI
      - name: Workflow Dispatch to app-notification-server K8S repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-notification-server
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Notification Server K8S CI
      - name: Workflow Dispatch to app-frontend-application repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: jhapy/app-frontend-application
          token: ${{ secrets.repos_access_token }}
          workflow: JHapy App Frontend Application CI
      - name: Slack Success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()